packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # React ecosystem
  react: 19.0.0
  react-dom: 19.0.0
  react-router-dom: 7.5.2

  # Module Federation
  '@module-federation/vite': 1.11.0
  '@module-federation/runtime': 0.24.1
  '@module-federation/native-federation-typescript': 0.6.0

  # TanStack Query
  '@tanstack/react-query': 5.74.4

  # Vite
  vite: 6.2.0
  '@vitejs/plugin-react': 4.3.4

  # TypeScript
  typescript: 5.7.2
  '@types/react': 19.0.10
  '@types/react-dom': 19.0.4
  '@types/node': 22.14.0
  '@types/express': 5.0.1

  # Build/Server
  express: 5.1.0
  cors: 2.8.5
  dotenv: 16.5.0

  # Vite plugins
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-top-level-await: 1.5.0

  # Testing
  '@testing-library/react': 16.3.0
  '@testing-library/jest-dom': 6.6.3

  # Linting
  '@eslint/js': 9.21.0
  typescript-eslint: 8.24.1

  # Utilities
  clsx: 2.1.1
