packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # React ecosystem
  react: 19.1.0
  react-dom: 19.1.0
  react-router-dom: 7.5.2

  # Module Federation
  '@module-federation/vite': 1.11.0
  '@module-federation/runtime': 0.24.1
  '@module-federation/dts-plugin': 0.24.1

  # TanStack Query
  '@tanstack/react-query': 5.74.4

  # Vite
  vite: 6.2.0
  '@vitejs/plugin-react': 4.7.0

  # TypeScript
  typescript: 5.7.2
  '@types/react': 19.1.0
  '@types/react-dom': 19.1.0
  '@types/node': 22.14.0
  '@types/express': 5.0.1

  # Build/Server
  express: 5.1.0
  cors: 2.8.5
  dotenv: 16.5.0

  # Vite plugins
  vite-plugin-css-injected-by-js: 3.5.2
  vite-plugin-top-level-await: 1.5.0
  '@antdevx/vite-plugin-hmr-sync': 1.1.2

  # Tailwind CSS
  tailwindcss: 4.1.0
  '@tailwindcss/cli': 4.1.0
  '@tailwindcss/vite': 4.1.0
  '@tailwindcss/postcss': 4.1.0

  # Testing
  '@testing-library/react': 16.3.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/user-event': 14.6.1

  # Linting
  '@eslint/js': 9.21.0
  typescript-eslint: 8.24.1

  # Utilities
  clsx: 2.1.1

  # Build tools
  tsup: 8.4.0
  autoprefixer: 10.4.21
  postcss: 8.5.3

  # Testing
  vitest: 3.2.4
  '@vitest/coverage-v8': 3.2.4
  jsdom: 26.0.0
