export { MediaHero } from './components/MediaHero'
export { Synopsis } from './components/Synopsis'
export { Crew } from './components/Crew'
export { Cast } from './components/Cast'
export { Photos } from './components/Photos'
export { SimilarSection } from './components/SimilarSection'
export { TrailersSection } from './components/TrailersSection'
