/**
 * @fileoverview TMDB HTTP Client package entry point.
 *
 * This package provides a type-safe HTTP client for the TMDB API,
 * generated from the official OpenAPI specification using heyAPI.
 *
 * **Note**: The `./client` folder is generated by heyAPI.
 * Run `pnpm generate` to create it.
 *
 * @example
 * ```typescript
 * // Import SDK functions
 * import { moviePopularList, movieDetails } from '@vite-mf-monorepo/tmdb-client'
 *
 * // Use with TanStack Query
 * import { moviePopularListOptions } from '@vite-mf-monorepo/tmdb-client'
 * const { data } = useQuery(moviePopularListOptions())
 * ```
 *
 * @see https://developer.themoviedb.org/docs - TMDB API Documentation
 * @see https://heyapi.dev - heyAPI Documentation
 */

// Re-export generated client
export * from './client'

// Re-export custom types
export type { TMDBError } from './types/errors'
