name: Deploy Host to Netlify

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed:
              - 'apps/host/**'
              - 'packages/**'

      - name: Build
        if: steps.changes.outputs.changed == 'true'
        run: pnpm prod

      - name: Install Netlify CLI
        if: steps.changes.outputs.changed == 'true'
        run: pnpm install -g netlify-cli

      - name: Deploy to Netlify (Production)
        if: steps.changes.outputs.changed == 'true'
        run: netlify deploy --prod --dir=apps/host/dist --site=$NETLIFY_SITE_ID_HOST --no-build --cwd apps/host
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID_HOST: ${{ secrets.NETLIFY_SITE_ID_HOST }}
